# -*- coding: utf-8 -*-
"""Day18.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1euKhnXDuEQCowysCIU2jhzOP_laODZJW
"""

import json  # importa el módulo para trabajar con JSON

with open('json_data', 'r') as file:  # abre el archivo 'json_data' en modo lectura
  tasks = json.load(file)  # carga el contenido JSON en la variable tasks
  print(tasks)  # imprime las tareas cargadas

import json

tasks = [  # define una lista inicial de tareas
  {"task": "Complete Project", "status": "Incomplete"}  # tarea de ejemplo
]

with open('tasks.json', 'w') as file:  # crea/reescribe 'tasks.json' con las tareas
  json.dump(tasks, file, indent=2)  # guarda la lista tasks en formato JSON con indentación

import json

with open('tasks.json', 'r') as file:  # abre el archivo tasks.json en modo lectura
  tasks = json.load(file)  # carga las tareas desde el archivo

tasks.append({"task": "Learn Python 2", "status": "Incomplete"})  # añade una nueva tarea a la lista

with open('tasks.json', 'w') as file:  # guarda la lista actualizada de tareas en el archivo
  json.dump(tasks, file, indent=2)  # escribe JSON con indentación

import json  # importa json para la aplicación
import os  # importa os para operaciones del sistema de archivos
# Mini To-Do App using JSON
import json
import os

# File for storing tasks
TASK_FILE = 'my_tasks.json'  # nombre del archivo donde se guardarán las tareas

# Ensure the tasks file exists
if not os.path.exists(TASK_FILE):  # verifica si el archivo no existe
  with open(TASK_FILE, 'w') as file:  # crea el archivo vacío
    json.dump([], file)  # escribe una lista vacía en el archivo

# Step 1: Load Tasks from JSON
def load_tasks():  # Step 1: Load Tasks from JSON
  with open(TASK_FILE, 'r') as file:  # abre el archivo de tareas en lectura
    return json.load(file)  # devuelve la lista de tareas cargada

# Step 2: Save Tasks to JSON
def save_tasks(tasks):  # Step 2: Save Tasks to JSON
  with open(TASK_FILE, 'w') as file:  # abre el archivo de tareas en escritura
    json.dump(tasks, file, indent=2)  # guarda la lista tasks en formato JSON

# Step 3: Add a new task
def add_task():  # Step 3: Add a new task
  task_name = input("Enter the task name: ").strip()  # pide el nombre de la tarea y elimina espacios
  tasks = load_tasks()  # carga tareas existentes
  tasks.append({"task": task_name, "status": "Incomplete"})  # añade la nueva tarea con estado Incomplete
  save_tasks(tasks)  # guarda la lista actualizada
  print(f'Task "{task_name}" added successfully!')  # confirma que la tarea fue añadida

# Step 4: View All Tasks
def view_tasks():  # Step 4: View All Tasks
  tasks = load_tasks()  # carga las tareas
  if tasks:  # si hay tareas
    print("\n--- To-Do List ---")  # título de la lista
    for idx, task in enumerate(tasks, start=1):  # itera con índice iniciando en 1
      print(f"{idx}. {task['task']} - {task['status']}")  # imprime número, nombre y estado de cada tarea
  else:  
    print("No tasks found.")  # indica que no hay tareas

# Step 5: Update Task Status
def update_status():  # Step 5: Update Task Status
  tasks = load_tasks()  # carga tareas existentes
  view_tasks()  # muestra las tareas actuales
  try:
    task_index = int(input("Enter the task number to update: ")) - 1  # pide el número de tarea y ajusta índice
    if 0 <= task_index < len(tasks):  # verifica que el índice sea válido
      new_status = input("Enter the new status (Complete/Incomplete): ").strip()  # pide el nuevo estado
      tasks[task_index]['status'] = new_status  # actualiza el estado de la tarea seleccionada
      save_tasks(tasks)  # guarda cambios
      print("Task status updated successfully!")  # confirma actualización
    else:  
      print("Invalid task number.")  # índice inválido
  except ValueError:
    print("Invalid input. Please enter a valid task number.")  # entrada no numérica

# Step 6: Delete a Task
def delete_task():  # Step 6: Delete a Task
  tasks = load_tasks()  # carga tareas
  view_tasks()  # muestra tareas
  try:
    task_index = int(input("Enter the task number to delete: ")) - 1  # pide número de tarea a eliminar
    if 0 <= task_index < len(tasks):  # verifica validez
      deleted_task = tasks.pop(task_index)  # elimina la tarea y la guarda en deleted_task
      save_tasks(tasks)  # guarda la lista actualizada
      print(f'Task "{deleted_task["task"]}" deleted successfully!')  # confirma eliminación
    else:  
      print("Invalid task number.")  # índice inválido
  except ValueError:
    print("Invalid input. Please enter a valid task number.")  # entrada no numérica

# Step 7: Display Menu
def display_menu():  # Step 7: Display Menu
  print("\n--- Mini To-Do App ---")  # muestra el título del menú
  print("1. Add a new task")  # opción para añadir tarea
  print("2. View all tasks")  # opción para ver todas las tareas
  print("3. Update Task status")  # opción para actualizar estado
  print("4. Delete a task")  # opción para eliminar tarea
  print("5. Exit")  # opción para salir

# Step 8: Main Program Loop
while True:  # Step 8: Main Program Loop
  display_menu()  # muestra el menú
  choice = input("Enter your choice (1-5): ").strip()  # pide la opción del usuario

  if choice == '1':  
    add_task()  # llama a la función para añadir tarea
  elif choice == '2':
    view_tasks()  # llama a la función para mostrar tareas
  elif choice == '3':
    update_status()  # llama a la función para actualizar estado
  elif choice == '4':
    delete_task()  # llama a la función para eliminar tarea
  elif choice == '5':
    print("Exiting the To-Do List App. Goodbye!")  # mensaje al salir
    break  # rompe el bucle principal
  else:
    print("Invalid choice. Please enter a number between 1 and 5.")  # opción inválida

